### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by YasirAyaz** [kolyvan/kxmovie#35]
Hi ,

 i have setup all the libraries and when i am building the app for device i got 30 compilation errors in KxMovieGLView and in KXMovieDecoder and i am posting some syntax errors here .. i am not sure which compiler should i use to compile the source code .. currently using default LLVM compiler 3.0 iOS SDK 5.0 

Here are some errors 

```
                    KxAudioFrame *frame = _audioFrames[0];
```

Error : subscript require size of interface "NSMutableArray" which is not constant in non-fragile ABI

```
_messageLabel.textAlignment = NSTextAlignmentCenter;
```

Error : Use of undeclared NSTextAlighnmentCenter;

and there are 30 errors . 

Can you please help me solving the above issue or if i am using wrong source code please let me know . 

Thanks

**Comment by kristopherjohnson** [comment]
You're going to have a hard time compiling with an old compiler. You will have to change a lot of things that look like this:

```
_audioFrames[0];
```

to this:

```
[_audioFrames objectAtIndex:0];
```

Similarly, using an old SDK means that you won't have some of the newer symbols and APis defined, like `NSTextAlignmentCenter`.  In this case, you can use the old name, `UITextAlignmentCenter` instead.

If possible, I'd recommend using current Xcode and current SDK. Note that the current Xcode and SDK can create apps that run on iOS 5.0. (However, you can't target some older hardware, like the iPhone 3G or 2nd-generation iPod Touch, because the ARMv6 architecture is no longer supported.)

**Comment by YasirAyaz** [comment]
Thank you so much to answer my questions i successfully resolved the issues
and i managed to build the app properly using ios6 sdk ...
And this project is awsome thanks for the great job .

**Comment by YasirAyaz** [comment]
Hi , 

I want to ask one more thing about the project.. I want to save stream in audio file to play offline .. can you please suggest me some solution for that ? is there any easy way to save the audio stream and play it offline ?

Thanks 
Yasir

**Comment by kolyvan** [comment]
Hi, 
Look at FFmpeg/doc/examples/muxing.c as example of writing audio file.
Best wishes.
